spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bookservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: "*$7yHZc6D7(95Tu>$sQ0wb*U2yu-"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sontug9xx@gmail.com
    password: mgtf gweh oxvq psup
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
cors: