spring:
  datasource:
    url: jdbc:mysql://your-prod-db:3306/BookService
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: validate  # production nên validate để tránh mất dữ liệu
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sontug9xx@gmail.com
    password: mgtf gweh oxvq psup
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
cors:
  allowed-origins: http://localhost:3000