spring:
  datasource:
    url: jdbc:mysql://bookstore.clsaao2oey1f.ap-southeast-2.rds.amazonaws.com/bookservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: d07Z~$LUybrSA$kbqDfs)qoVQSzC
  jpa:
    hibernate:
      ddl-auto: validate  # production nên validate để tránh mất dữ liệu
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sontug9xx@gmail.com
    password: mgtf gweh oxvq psup
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
cors: